-- 2Block Music - Supabase init schema
-- Execute in Supabase SQL Editor.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Core tables
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null default '2Block',
  cover_url text,
  lyrics text,
  file text,
  storage_path text not null unique,
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  is_published boolean not null default false,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.song_downloads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  downloaded_at timestamptz not null default now(),
  app_version text,
  device_id text,
  unique (user_id, song_id)
);

create table if not exists public.listening_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  session_id text not null,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  seconds_listened integer not null check (seconds_listened >= 0),
  is_offline boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, song_id, session_id),
  check (ended_at >= started_at)
);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  );
$$;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
create index if not exists idx_profiles_role on public.profiles(role);

create index if not exists idx_songs_published on public.songs(is_published, created_at desc);
create index if not exists idx_songs_created_by on public.songs(created_by);

create index if not exists idx_song_downloads_song on public.song_downloads(song_id);
create index if not exists idx_song_downloads_user_date on public.song_downloads(user_id, downloaded_at desc);

create index if not exists idx_listening_song_date on public.listening_events(song_id, started_at desc);
create index if not exists idx_listening_user_date on public.listening_events(user_id, started_at desc);
create index if not exists idx_listening_offline on public.listening_events(is_offline);

-- ---------------------------------------------------------------------------
-- Updated-at trigger
-- ---------------------------------------------------------------------------
create or replace function public.tg_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute procedure public.tg_set_updated_at();

drop trigger if exists trg_songs_updated_at on public.songs;
create trigger trg_songs_updated_at
before update on public.songs
for each row execute procedure public.tg_set_updated_at();

-- ---------------------------------------------------------------------------
-- Auth -> profile sync trigger
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, coalesce(new.email, ''), 'user')
  on conflict (id) do update
  set email = excluded.email;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.handle_user_email_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.email is distinct from old.email then
    update public.profiles
    set email = coalesce(new.email, '')
    where id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_email_updated on auth.users;
create trigger on_auth_user_email_updated
after update of email on auth.users
for each row execute procedure public.handle_user_email_update();

-- ---------------------------------------------------------------------------
-- Optional RPC for downloads registration
-- ---------------------------------------------------------------------------
create or replace function public.register_song_download(
  p_song_id bigint,
  p_app_version text default null,
  p_device_id text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  insert into public.song_downloads (user_id, song_id, app_version, device_id)
  values (auth.uid(), p_song_id, p_app_version, p_device_id)
  on conflict (user_id, song_id)
  do update set downloaded_at = now();
end;
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.songs enable row level security;
alter table public.song_downloads enable row level security;
alter table public.listening_events enable row level security;

-- profiles
drop policy if exists "profiles_select_self_or_admin" on public.profiles;
create policy "profiles_select_self_or_admin"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles_update_self_or_admin" on public.profiles;
create policy "profiles_update_self_or_admin"
on public.profiles
for update
to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

-- songs
drop policy if exists "songs_select_published_or_admin" on public.songs;
create policy "songs_select_published_or_admin"
on public.songs
for select
to authenticated
using (is_published = true or public.is_admin());

drop policy if exists "songs_insert_admin" on public.songs;
create policy "songs_insert_admin"
on public.songs
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "songs_update_admin" on public.songs;
create policy "songs_update_admin"
on public.songs
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "songs_delete_admin" on public.songs;
create policy "songs_delete_admin"
on public.songs
for delete
to authenticated
using (public.is_admin());

-- song_downloads
drop policy if exists "downloads_select_self_or_admin" on public.song_downloads;
create policy "downloads_select_self_or_admin"
on public.song_downloads
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "downloads_insert_self" on public.song_downloads;
create policy "downloads_insert_self"
on public.song_downloads
for insert
to authenticated
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists "downloads_update_self_or_admin" on public.song_downloads;
create policy "downloads_update_self_or_admin"
on public.song_downloads
for update
to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

-- listening_events
drop policy if exists "events_select_self_or_admin" on public.listening_events;
create policy "events_select_self_or_admin"
on public.listening_events
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "events_insert_self" on public.listening_events;
create policy "events_insert_self"
on public.listening_events
for insert
to authenticated
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists "events_update_self_or_admin" on public.listening_events;
create policy "events_update_self_or_admin"
on public.listening_events
for update
to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

-- ---------------------------------------------------------------------------
-- Storage bucket + policies (private bucket)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'songs-private',
  'songs-private',
  false,
  104857600,
  array['audio/mpeg', 'audio/mp4', 'audio/x-m4a', 'audio/aac', 'audio/wav', 'audio/ogg']
)
on conflict (id) do nothing;

drop policy if exists "storage_admin_manage_songs_private" on storage.objects;
create policy "storage_admin_manage_songs_private"
on storage.objects
for all
to authenticated
using (bucket_id = 'songs-private' and public.is_admin())
with check (bucket_id = 'songs-private' and public.is_admin());

drop policy if exists "storage_auth_read_published_song_files" on storage.objects;
create policy "storage_auth_read_published_song_files"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'songs-private'
  and exists (
    select 1
    from public.songs s
    where s.storage_path = name
      and s.is_published = true
  )
);

-- ---------------------------------------------------------------------------
-- Admin dashboard views
-- ---------------------------------------------------------------------------
create or replace view public.admin_dashboard_kpis as
select
  (select count(*) from public.listening_events where public.is_admin()) as total_events,
  (select count(distinct user_id) from public.listening_events where public.is_admin()) as unique_users,
  (select coalesce(sum(seconds_listened), 0) from public.listening_events where public.is_admin()) as total_seconds,
  (select count(*) from public.song_downloads where public.is_admin()) as total_downloads;

create or replace view public.admin_song_stats as
select
  s.id as song_id,
  s.title,
  s.artist,
  count(le.id) as plays_count,
  count(distinct le.user_id) as listeners_count,
  coalesce(sum(le.seconds_listened), 0) as seconds_total
from public.songs s
left join public.listening_events le on le.song_id = s.id
where public.is_admin()
group by s.id, s.title, s.artist
order by plays_count desc, seconds_total desc;

create or replace view public.admin_user_activity as
select
  p.id as user_id,
  p.email,
  count(distinct sd.song_id) as songs_downloaded,
  count(le.id) as listening_events,
  coalesce(sum(le.seconds_listened), 0) as seconds_total,
  max(le.started_at) as last_activity_at
from public.profiles p
left join public.song_downloads sd on sd.user_id = p.id
left join public.listening_events le on le.user_id = p.id
where public.is_admin()
group by p.id, p.email
order by seconds_total desc nulls last, listening_events desc;

create or replace view public.admin_listening_events_detailed as
select
  le.id,
  le.user_id,
  p.email as user_email,
  le.song_id,
  s.title as song_title,
  s.artist as song_artist,
  le.session_id,
  le.started_at,
  le.ended_at,
  le.seconds_listened,
  le.is_offline,
  le.created_at
from public.listening_events le
join public.profiles p on p.id = le.user_id
join public.songs s on s.id = le.song_id
where public.is_admin()
order by le.started_at desc;

commit;
