-- 2Block Music - schema extensions
-- Execute after 001_init_schema.sql

begin;

-- ---------------------------------------------------------------------------
-- Extra tables
-- ---------------------------------------------------------------------------
create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  target_type text not null,
  target_id text,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_admin_audit_created_at
  on public.admin_audit_logs(created_at desc);

create index if not exists idx_admin_audit_admin
  on public.admin_audit_logs(admin_user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Data integrity upgrades
-- ---------------------------------------------------------------------------
alter table public.listening_events
  drop constraint if exists listening_events_seconds_vs_range_check;

alter table public.listening_events
  add constraint listening_events_seconds_vs_range_check
  check (
    seconds_listened <= greatest(
      0,
      floor(extract(epoch from (ended_at - started_at)))
    )
  );

-- ---------------------------------------------------------------------------
-- Default song ownership + audit
-- ---------------------------------------------------------------------------
create or replace function public.tg_songs_set_created_by()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.created_by is null and auth.uid() is not null then
    new.created_by = auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_songs_set_created_by on public.songs;
create trigger trg_songs_set_created_by
before insert on public.songs
for each row execute procedure public.tg_songs_set_created_by();

create or replace function public.tg_admin_audit_songs()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid;
begin
  actor := auth.uid();
  if actor is null or not public.is_admin() then
    return coalesce(new, old);
  end if;

  if tg_op = 'INSERT' then
    insert into public.admin_audit_logs (admin_user_id, action, target_type, target_id, payload)
    values (actor, 'create', 'song', new.id::text, to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.admin_audit_logs (admin_user_id, action, target_type, target_id, payload)
    values (
      actor,
      'update',
      'song',
      new.id::text,
      jsonb_build_object('old', to_jsonb(old), 'new', to_jsonb(new))
    );
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.admin_audit_logs (admin_user_id, action, target_type, target_id, payload)
    values (actor, 'delete', 'song', old.id::text, to_jsonb(old));
    return old;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_admin_audit_songs on public.songs;
create trigger trg_admin_audit_songs
after insert or update or delete on public.songs
for each row execute procedure public.tg_admin_audit_songs();

-- ---------------------------------------------------------------------------
-- RPC: sync listening events in batch (offline -> online)
-- ---------------------------------------------------------------------------
create or replace function public.sync_listening_events(
  p_events jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_count integer := 0;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  insert into public.listening_events (
    user_id,
    song_id,
    session_id,
    started_at,
    ended_at,
    seconds_listened,
    is_offline
  )
  select
    v_user_id,
    (e->>'song_id')::bigint,
    e->>'session_id',
    (e->>'started_at')::timestamptz,
    (e->>'ended_at')::timestamptz,
    greatest(0, (e->>'seconds_listened')::integer),
    coalesce((e->>'is_offline')::boolean, false)
  from jsonb_array_elements(p_events) as e
  where (e->>'song_id') is not null
    and (e->>'session_id') is not null
  on conflict (user_id, song_id, session_id)
  do update set
    ended_at = excluded.ended_at,
    seconds_listened = greatest(public.listening_events.seconds_listened, excluded.seconds_listened),
    is_offline = public.listening_events.is_offline or excluded.is_offline;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

grant execute on function public.sync_listening_events(jsonb) to authenticated;

-- ---------------------------------------------------------------------------
-- RPC: admin publish/unpublish song
-- ---------------------------------------------------------------------------
create or replace function public.admin_set_song_published(
  p_song_id bigint,
  p_is_published boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Forbidden';
  end if;

  update public.songs
  set is_published = p_is_published,
      updated_at = now()
  where id = p_song_id;
end;
$$;

grant execute on function public.admin_set_song_published(bigint, boolean) to authenticated;

-- ---------------------------------------------------------------------------
-- Materialized daily stats + refresh RPC
-- ---------------------------------------------------------------------------
create materialized view if not exists public.mv_song_stats_daily as
select
  date_trunc('day', le.started_at)::date as day,
  le.song_id,
  count(*)::bigint as plays_count,
  count(distinct le.user_id)::bigint as listeners_count,
  coalesce(sum(le.seconds_listened), 0)::bigint as seconds_total
from public.listening_events le
group by 1, 2;

create unique index if not exists idx_mv_song_stats_daily_unique
  on public.mv_song_stats_daily(day, song_id);

create or replace function public.refresh_song_stats_daily()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- In SQL editor/admin context, auth.uid() is often NULL.
  -- Allow execution when there is no authenticated JWT user.
  if auth.uid() is not null and not public.is_admin() then
    raise exception 'Forbidden';
  end if;
  refresh materialized view concurrently public.mv_song_stats_daily;
end;
$$;

grant execute on function public.refresh_song_stats_daily() to authenticated;

-- ---------------------------------------------------------------------------
-- RLS for extension tables
-- ---------------------------------------------------------------------------
alter table public.app_settings enable row level security;
alter table public.admin_audit_logs enable row level security;

drop policy if exists "app_settings_admin_read" on public.app_settings;
create policy "app_settings_admin_read"
on public.app_settings
for select
to authenticated
using (public.is_admin());

drop policy if exists "app_settings_admin_write" on public.app_settings;
create policy "app_settings_admin_write"
on public.app_settings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin_audit_logs_admin_read" on public.admin_audit_logs;
create policy "admin_audit_logs_admin_read"
on public.admin_audit_logs
for select
to authenticated
using (public.is_admin());

drop policy if exists "admin_audit_logs_admin_insert" on public.admin_audit_logs;
create policy "admin_audit_logs_admin_insert"
on public.admin_audit_logs
for insert
to authenticated
with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Read-only dashboard view on materialized stats
-- ---------------------------------------------------------------------------
create or replace view public.admin_song_stats_daily as
select
  d.day,
  d.song_id,
  s.title,
  s.artist,
  d.plays_count,
  d.listeners_count,
  d.seconds_total
from public.mv_song_stats_daily d
join public.songs s on s.id = d.song_id
where public.is_admin()
order by d.day desc, d.plays_count desc;

commit;
