-- 2Block Music - push tokens registry for FCM notifications
-- Execute after 001_init_schema.sql and 002_schema_extensions.sql

begin;

create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  token text not null unique,
  platform text not null default 'unknown',
  app_version text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_push_tokens_user
  on public.push_tokens(user_id, updated_at desc);

create index if not exists idx_push_tokens_active
  on public.push_tokens(is_active, updated_at desc);

create or replace function public.register_push_token(
  p_token text,
  p_platform text default 'unknown',
  p_app_version text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if p_token is null or length(trim(p_token)) = 0 then
    raise exception 'Token is required';
  end if;

  insert into public.push_tokens (
    user_id,
    token,
    platform,
    app_version,
    is_active,
    updated_at
  )
  values (
    auth.uid(),
    trim(p_token),
    coalesce(nullif(trim(p_platform), ''), 'unknown'),
    p_app_version,
    true,
    now()
  )
  on conflict (token)
  do update set
    user_id = auth.uid(),
    platform = excluded.platform,
    app_version = excluded.app_version,
    is_active = true,
    updated_at = now();
end;
$$;

create or replace function public.unregister_push_token(
  p_token text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return;
  end if;

  if p_token is null or length(trim(p_token)) = 0 then
    return;
  end if;

  update public.push_tokens
  set is_active = false,
      updated_at = now()
  where token = trim(p_token)
    and user_id = auth.uid();
end;
$$;

alter table public.push_tokens enable row level security;

drop policy if exists "push_tokens_owner_read" on public.push_tokens;
create policy "push_tokens_owner_read"
on public.push_tokens
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "push_tokens_owner_insert" on public.push_tokens;
create policy "push_tokens_owner_insert"
on public.push_tokens
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "push_tokens_owner_update" on public.push_tokens;
create policy "push_tokens_owner_update"
on public.push_tokens
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "push_tokens_owner_delete" on public.push_tokens;
create policy "push_tokens_owner_delete"
on public.push_tokens
for delete
to authenticated
using (auth.uid() = user_id);

grant execute on function public.register_push_token(text, text, text) to authenticated;
grant execute on function public.unregister_push_token(text) to authenticated;

commit;

