-- 2Block Music - public site metrics
-- Execute after 001_init_schema.sql ... 013_mobile_release_distribution.sql

begin;

create table if not exists public.site_download_events (
  id bigint generated by default as identity primary key,
  source text not null default 'site',
  created_at timestamptz not null default now(),
  constraint site_download_events_source_check
    check (source in ('site', 'campaign', 'social', 'update', 'direct'))
);

create index if not exists idx_site_download_events_created_at
  on public.site_download_events(created_at desc);

create index if not exists idx_site_download_events_source_created_at
  on public.site_download_events(source, created_at desc);

alter table public.site_download_events enable row level security;

create or replace function public.track_public_download(
  p_source text default 'site'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source text;
begin
  v_source := lower(trim(coalesce(p_source, 'site')));

  if v_source = '' then
    v_source := 'site';
  end if;

  if v_source not in ('site', 'campaign', 'social', 'update', 'direct') then
    v_source := 'site';
  end if;

  insert into public.site_download_events (source)
  values (v_source);
end;
$$;

create or replace function public.get_public_site_metrics()
returns table (
  app_downloads bigint,
  active_fans_30d bigint,
  published_songs bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    (select count(*)::bigint from public.site_download_events),
    (
      select count(distinct le.user_id)::bigint
      from public.listening_events le
      where le.started_at >= now() - interval '30 days'
    ),
    (
      select count(*)::bigint
      from public.songs s
      where s.is_published = true
    );
$$;

revoke all on public.site_download_events from anon, authenticated;
revoke execute on function public.track_public_download(text) from public;
revoke execute on function public.get_public_site_metrics() from public;

grant execute on function public.track_public_download(text) to anon, authenticated;
grant execute on function public.get_public_site_metrics() to anon, authenticated;

commit;
