-- 2Block Music - support declarations from mobile USSD flow
-- Execute after 001_init_schema.sql and 012_security_hardening.sql

begin;

create table if not exists public.support_declarations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount_fcfa integer not null,
  channel text not null default 'ussd',
  app_version text,
  created_at timestamptz not null default now(),
  constraint support_declarations_amount_check
    check (amount_fcfa > 0 and amount_fcfa <= 100000000),
  constraint support_declarations_channel_check
    check (channel in ('ussd', 'manual', 'other'))
);

create index if not exists idx_support_declarations_created_at
  on public.support_declarations(created_at desc);

create index if not exists idx_support_declarations_user_created_at
  on public.support_declarations(user_id, created_at desc);

alter table public.support_declarations enable row level security;

drop policy if exists "support_declarations_select_self_or_admin"
  on public.support_declarations;
create policy "support_declarations_select_self_or_admin"
on public.support_declarations
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

create or replace function public.register_support_declaration(
  p_amount_fcfa integer,
  p_channel text default 'ussd',
  p_app_version text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_channel text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if p_amount_fcfa is null or p_amount_fcfa <= 0 or p_amount_fcfa > 100000000 then
    raise exception 'Invalid amount';
  end if;

  v_channel := lower(trim(coalesce(p_channel, 'ussd')));
  if v_channel = '' then
    v_channel := 'ussd';
  end if;

  if v_channel not in ('ussd', 'manual', 'other') then
    v_channel := 'ussd';
  end if;

  insert into public.support_declarations (
    user_id,
    amount_fcfa,
    channel,
    app_version
  )
  values (
    auth.uid(),
    p_amount_fcfa,
    v_channel,
    nullif(trim(coalesce(p_app_version, '')), '')
  );
end;
$$;

revoke all on public.support_declarations from anon, authenticated;
revoke execute on function public.register_support_declaration(integer, text, text) from public;
grant select on public.support_declarations to authenticated;
grant execute on function public.register_support_declaration(integer, text, text) to authenticated;

commit;
