-- 2Block Music - likes and comments on songs
-- Execute after 001_init_schema.sql, 006_add_profile_full_name.sql and 012_security_hardening.sql

begin;

create table if not exists public.song_likes (
  song_id bigint not null references public.songs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (song_id, user_id)
);

create table if not exists public.song_comments (
  id bigint generated by default as identity primary key,
  song_id bigint not null references public.songs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint song_comments_body_check
    check (char_length(trim(body)) between 1 and 500)
);

create index if not exists idx_song_likes_song_created
  on public.song_likes(song_id, created_at desc);

create index if not exists idx_song_comments_song_created
  on public.song_comments(song_id, created_at desc);

create index if not exists idx_song_comments_user_created
  on public.song_comments(user_id, created_at desc);

drop trigger if exists trg_song_comments_updated_at on public.song_comments;
create trigger trg_song_comments_updated_at
before update on public.song_comments
for each row execute procedure public.tg_set_updated_at();

alter table public.song_likes enable row level security;
alter table public.song_comments enable row level security;

create or replace function public.get_song_social_counts(
  p_song_ids bigint[]
)
returns table (
  song_id bigint,
  likes_count bigint,
  comments_count bigint,
  viewer_has_liked boolean
)
language sql
stable
security definer
set search_path = public
as $$
  with requested as (
    select distinct unnest(coalesce(p_song_ids, '{}')) as song_id
  ),
  visible_songs as (
    select r.song_id
    from requested r
    join public.songs s on s.id = r.song_id
    where s.is_published = true or public.is_admin()
  ),
  likes as (
    select sl.song_id, count(*)::bigint as likes_count
    from public.song_likes sl
    join visible_songs vs on vs.song_id = sl.song_id
    group by sl.song_id
  ),
  comments as (
    select sc.song_id, count(*)::bigint as comments_count
    from public.song_comments sc
    join visible_songs vs on vs.song_id = sc.song_id
    group by sc.song_id
  )
  select
    vs.song_id,
    coalesce(l.likes_count, 0) as likes_count,
    coalesce(c.comments_count, 0) as comments_count,
    case
      when auth.uid() is null then false
      else exists (
        select 1
        from public.song_likes sl
        where sl.song_id = vs.song_id
          and sl.user_id = auth.uid()
      )
    end as viewer_has_liked
  from visible_songs vs
  left join likes l on l.song_id = vs.song_id
  left join comments c on c.song_id = vs.song_id
  order by vs.song_id;
$$;

drop function if exists public.toggle_song_like(bigint);
create or replace function public.toggle_song_like(
  p_song_id bigint
)
returns table (
  song_id bigint,
  liked boolean,
  likes_count bigint,
  comments_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_liked boolean;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if not exists (
    select 1
    from public.songs s
    where s.id = p_song_id
      and (s.is_published = true or public.is_admin())
  ) then
    raise exception 'Song not found';
  end if;

  if exists (
    select 1
    from public.song_likes sl
    where sl.song_id = p_song_id
      and sl.user_id = v_user_id
  ) then
    delete from public.song_likes
    where song_id = p_song_id
      and user_id = v_user_id;
    v_liked := false;
  else
    insert into public.song_likes (song_id, user_id)
    values (p_song_id, v_user_id);
    v_liked := true;
  end if;

  return query
  select
    p_song_id,
    v_liked,
    (select count(*)::bigint from public.song_likes where song_id = p_song_id),
    (select count(*)::bigint from public.song_comments where song_id = p_song_id);
end;
$$;

drop function if exists public.get_song_comments(bigint, integer, integer);
create or replace function public.get_song_comments(
  p_song_id bigint,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  comment_id bigint,
  song_id bigint,
  user_id uuid,
  user_name text,
  body text,
  created_at timestamptz,
  is_mine boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    sc.id as comment_id,
    sc.song_id,
    sc.user_id,
    coalesce(nullif(trim(p.full_name), ''), split_part(p.email, '@', 1), 'Utilisateur') as user_name,
    sc.body,
    sc.created_at,
    case
      when auth.uid() is null then false
      else sc.user_id = auth.uid()
    end as is_mine
  from public.song_comments sc
  join public.songs s on s.id = sc.song_id
  join public.profiles p on p.id = sc.user_id
  where sc.song_id = p_song_id
    and (s.is_published = true or public.is_admin())
  order by sc.created_at desc
  limit greatest(1, least(coalesce(p_limit, 50), 100))
  offset greatest(coalesce(p_offset, 0), 0);
$$;

drop function if exists public.add_song_comment(bigint, text);
create or replace function public.add_song_comment(
  p_song_id bigint,
  p_body text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_body text;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if not exists (
    select 1
    from public.songs s
    where s.id = p_song_id
      and (s.is_published = true or public.is_admin())
  ) then
    raise exception 'Song not found';
  end if;

  v_body := trim(coalesce(p_body, ''));
  if char_length(v_body) < 1 or char_length(v_body) > 500 then
    raise exception 'Invalid comment';
  end if;

  insert into public.song_comments (song_id, user_id, body)
  values (p_song_id, v_user_id, v_body);
end;
$$;

drop function if exists public.delete_song_comment(bigint);
create or replace function public.delete_song_comment(
  p_comment_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  delete from public.song_comments sc
  where sc.id = p_comment_id
    and (sc.user_id = v_user_id or public.is_admin());

  if not found then
    raise exception 'Comment not found';
  end if;
end;
$$;

revoke all on public.song_likes from anon, authenticated;
revoke all on public.song_comments from anon, authenticated;

revoke execute on function public.get_song_social_counts(bigint[]) from public;
revoke execute on function public.toggle_song_like(bigint) from public;
revoke execute on function public.get_song_comments(bigint, integer, integer) from public;
revoke execute on function public.add_song_comment(bigint, text) from public;
revoke execute on function public.delete_song_comment(bigint) from public;

grant execute on function public.get_song_social_counts(bigint[]) to anon, authenticated;
grant execute on function public.get_song_comments(bigint, integer, integer) to anon, authenticated;
grant execute on function public.toggle_song_like(bigint) to authenticated;
grant execute on function public.add_song_comment(bigint, text) to authenticated;
grant execute on function public.delete_song_comment(bigint) to authenticated;

commit;
